spring.application.name=discovery-server
server.port=${SERVER_PORT:8761}

# Este e um servidor Eureka: nao se registra nem busca o proprio registro
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:${server.port}/eureka/
